/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.9.1.
 * To regenerate, run `npx convex codegen`.
 * @module
 */

import type { ApiFromModules } from "convex/api";
import type * as accessWhisper from "../accessWhisper";
import type * as createWhisper from "../createWhisper";
import type * as deleteExpired from "../deleteExpired";
import type * as expireNow from "../expireNow";
import type * as fileUploadURL from "../fileUploadURL";
import type * as readAccessLog from "../readAccessLog";
import type * as readExpiration from "../readExpiration";
import type * as readExpirationError from "../readExpirationError";
import type * as readSecret from "../readSecret";
import type * as recordAccessGeolocation from "../recordAccessGeolocation";
import type * as security from "../security";

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about the arguments and return
 * types of your app's query and mutation functions.
 *
 * This type should be used with type-parameterized classes like
 * `ConvexReactClient` to create app-specific types.
 */
export type API = ApiFromModules<{
  accessWhisper: typeof accessWhisper;
  createWhisper: typeof createWhisper;
  deleteExpired: typeof deleteExpired;
  expireNow: typeof expireNow;
  fileUploadURL: typeof fileUploadURL;
  readAccessLog: typeof readAccessLog;
  readExpiration: typeof readExpiration;
  readExpirationError: typeof readExpirationError;
  readSecret: typeof readSecret;
  recordAccessGeolocation: typeof recordAccessGeolocation;
  security: typeof security;
}>;
